project:
  title: "Balloon magnetometry"
  type: website
  pre-render: make
  output-dir: _site

execute:
  freeze: true

website:
  title: "Balloons"
  site-url: "https://apnielsen.com/high-altitude-balloon"
  description: "This is a summary of notes for launching a high-altitude balloon"
  
  navbar:
    search: true

    left:
      - text: "Home page"
        href: "https://apnielsen.com/"
      
    right:
      - icon: github
        href: https://github.com/anielsen001/high-altitude-balloon

  sidebar:
    logo: _sources/eclipse/balloon_launch_eclipse_thumb.jpg
    style: "floating"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Calculators"
        contents:
        - text: "Horizon calculator"
          href: calculators/horizon.qmd
        - text: "Solar elevation at location"
          href: calculators/solar_elevation.qmd
        - text: "Solar elevation at latitude"
          href: calculators/solar_elevation2.qmd
        - text: "Float parameters"
          href: calculators/float2.qmd
      - section: "Launches"
        contents: launches/*.qmd
      - text: "WSPR Tracking"
        href: wspr/tracking.qmd
      - text: "References"
        href: refs/refs.qmd
  
format:
  html:
    theme:
      - cosmo
    lightbox: auto
    code-fold: show
    code-tools: true
    toc: true
     
bibliography:
  - refs/refs.bib
