## Default program

This is the default program

```basic
10 GPS 360
TELE
GOTO 10
```

## Rules

No blank lines in the code. This causes the code to stop.

you may need to both save and then also compile.

## Testing program

This is a program for testing. Each print statement prints out the current time before the message.

There's a different syntax running from command line vs in a program. 

- in a program use 
```basic
RUN "TEST"
```
- at command line use
```basic
RUN TEST
```

The TELE statement waits until the proper time to transmit, which could be up to 10 minutes.

C is the transmission count - increment everytime a transmission occurs. used to see if transmissions are missing. if balloon loses power this will reset
N is a counter used for the BLINK program to set the number of times to blink the led


### initialization program 

- start the system in low power
- Switch to high power after N loops have occured

- C is for counting how many loops have happened since the system powered on
- N is the count that switches to high power
  - this is a zero-based count, first pass thru loop is C = 0
- T is the test setting variable
  - T = 1 is test
  - T = 0 is no test
  - logic should be `IF T = 1` then we are in test

INIT
```BASIC
LET CH = 109
LET HP = 0
LET C = 0
LET N = 2
LET T = 1
PRINT "HOST USB:    #US"
PRINT "HIGH POWER:  #HP"
PRINT "FREQUENCY:   #FQ"
PRINT "CHANNEL:     #CH"
PRINT "CALLSIGN:    #CS"
PRINT "TEMPERATURE: #TK"
IF T = 1
PRINT "FAKE GPS/TELE MODE"
ELSE
PRINT "REAL GPS/TELE MODE"
ENDIF
PRINT "INIT DONE"
```

### SHOW - show state of important variables

```basic
PRINT "SHOW START"
PRINT "LLH:  #LT #LN #AT"
PRINT "GPS:  VALID: #GV LOCK: #GL SPEED: #GS CALIB: #CL"
PRINT "GPS:  NSAT:  #SC"
PRINT "CNT:  #VC"
PRINT "TEMP: #TK"
PRINT "POWR: #HP"
PRINT "SHOW DONE"
```

### GPS related

The logic here is a way to enable/disable GPS for indoor testing

MYGPS
```basic
RUN "LEDOFF"
IF T = 1
GPS 360
ELSE
PRINT "GPS 360 HERE"
DELAY 2000
ENDIF
RUN "LEDON"
```

### Telemetry

The logic here is a way to enable/disable telemetry for indoor testing


```basic
PRINT "TELEMETRY START"
RUN "LEDOFF"
IF T = 1
TELE
ELSE
PRINT "TELE HERE"
DELAY 2000
ENDIF
RUN "LEDON"
PRINT "TELEMETRY END"
```

### TRACKER program

```basic
PRINT "START TRACKER2"
RUN "INIT"
RUN "SHOW"
PRINT "INITIAL GPS"
RUN "MYGPS"
10 PRINT "LOOP AT #VC"
RUN "SHOW"
RUN "MYTELE"
LET C = C + 1
IF C > N
    LET HP = 1
ENDIF
RUN "MYGPS"
GOTO 10
```

### Blink LED program

The value N is used to control how often to flash

BLINK
```BASIC
PRINT "BLINK #VN"
DELAY 100
FOR I = 1 TO N
OUT 19 1
DELAY 100
OUT 19 0
DELAY 100
NEXT
```

LEDON
```BASIC
OUT 19 1
```

LEDOFF
```BASIC
OUT 19 0
```

### Main program

The BLINK program seems to cause the code to hang up, so not using it.

```basic
RUN "INIT"
10 GPS 360
LET C = C + 1
RUN "SHOW"
PRINT "START TELE"
TELE
PRINT "END TELE"
GOTO 10

```

### Show program

shows variables in the terminal

```basic
PRINT "LLH:  #LT #LN #AT"
PRINT "GPS:  VALID: #GV LOCK: #GL SPEED: #GS CALIB: #CL"
PRINT "CNT:  #VC"
PRINT "TEMP: #TK"
```

### Count program

keep a counter with the value stored in a file

CNTINIT program

opens for append, if it's empy, then write the current counter value

```basic
FILE 1 "A" "COUNTLOG"
IF FILEEOF 1 = 1
   PRINT "COUNTLOG EMPTY"
   FILEWR 1 C
ENDIF
```

CNTINCR

```basic

```

## Issues

### Firmware 1.00.05

the CH variable prints differently than expected. I think the tag version and non-tagged version should both work but does not appear to.

```text
$ PRINT CH
325
$ PRINT "#CH"

$ PRINT "CHANNEL: #CH"
CHANNEL:
$ PRINT CH
325
$
```
