## Configuration

- Firmware: 1.01.001 (upgraded 26 march 2026)
- Callsign: KF8EEZ
- Band: 20m
- Channel: 244
  - 6 minutes after, 14,097,020 MHz
- Autostart: TRACKER2
- QRP-labs S/N: 21831

## HF antenna

top and bottom arms from U4B about 5 inches. Antenna arms should be about 198.84837766362426 inches. I created two spools of 200 inch long each. For both, need to cut about 6.16 inches off of the spooled wire.

### Upper

```{python}
print(200 + 5 - 198.84) 
```
= 6.16 in

### Lower

```{python}
print(200 + 5 - 198.84) 
```
= 6.16 in



## GPS antenna

Twisted pair feed, 50mm arms. Tested. Good GPS fixes.

## Programs

### Variables

- C is the count of transmissions since wake up
- N is the number of transmissions before switching to high-power (0-based)
- T is a flag for test mode
  - T=1 - test mode
  - T=0 - live mode - must be in live mode for flight
- B is the number of times to blink the led, set to 5

### TRACKER2

This is the primary program. The MYTELE and MYGPS subroutines enable control of a test mode which doesn't need GPS or ability to transmit.

```
PRINT "START TRACKER2"
RUN "INIT"
RUN "SHOW"
LET B = 5
RUN "BLINK"
PRINT "INITIAL GPS"
RUN "MYGPS"
LET B = 2
RUN "BLINK"
10 PRINT "LOOP AT #VC"
RUN "SHOW"
RUN "MYTELE"
LET C = C + 1
IF C > N
    LET HP = 1
ENDIF
RUN "MYGPS"
GOTO 10
```

### INIT

Initialization should run once on power up.

```
PRINT "INIT START"
LET CH = 567
LET HP = 0
LET C = 0
LET N = 2
LET T = 1
LET B = 5
PRINT "HOST USB:    #US"
PRINT "HIGH POWER:  #HP"
PRINT "FREQUENCY:   #FQ"
PRINT "CHANNEL:     #CH"
PRINT "CALLSIGN:    #CS"
PRINT "TEMPERATURE: #TK"
IF T = 1
PRINT "FAKE GPS/TELE MODE"
ELSE
PRINT "REAL GPS/TELE MODE"
ENDIF
PRINT "INIT DONE"
```

### SHOW

Prints out the current state

```
PRINT "SHOW START"
PRINT "LLH:  #LT #LN #AT"
PRINT "GPS:  VALID: #GV LOCK: #GL SPEED: #GS CALIB: #CL"
PRINT "GPS:  NSAT:  #SC"
PRINT "CNT:  #VC"
PRINT "TEMP: #TK"
PRINT "POWR: #HP"
PRINT "SHOW DONE"
```

### MYGPS

This is my GPS program, it lets you use the GPS in a test mode without an actual signal. Don't acquire GPS if in test mode (T=1)

```
PRINT "GPS START"
RUN "LEDOFF"
IF T = 0
PRINT "REAL GPS"
GPS 360
ELSE
PRINT "FAKE GPS"
DELAY 2000
ENDIF
RUN "LEDON"
PRINT "GPS END"
```

### MYTELE

Don't transmit if in test mode (T=1)

```
PRINT "TELEMETRY START"
RUN "LEDOFF"
IF T = 0
PRINT "REAL TELE"
TELE
ELSE
PRINT "FAKE TELE"
DELAY 2000
ENDIF
RUN "LEDON"
PRINT "TELEMETRY END"
```

### LEDOFF

Turn LED off

```
OUT 19 0
```

### LEDON

Turn LED on

```
OUT 19 1
```

### BLINK

turns led on and off B times. you must set b first

```
FOR L = 0 TO B
RUN "LEDON"
DELAY 100
RUN "LEDOFF"
DELAY 100
NEXT
```
