## Kalman tracking filter

This is a derivation of a basic Kalman fitler to smooth and update the WSPR responses. 

## State vector

I'm assuming that they balloon moves with the airmass and the filter models postion and velocity, assuming constant velocity.  Acceleration is treated as process noise. 

Position is measured in latitude, longitude and height above the WGS-84 ellipsoid, this is the geodetic reference frame. Velocity is measured in north, east, down coordiantes using meters, this is the navigation reference frame.

The state evolves in the most generic form, which does not account for motion around the earth.

\begin{equation}
x_{k+1} = v_k \Delta t + x_k
\end{equation}

A good description of the Earth rotation equations and derivation can be found in [Woodburn's INU library](https://gitlab.com/davidwoodburn/inu). 

\begin{equation}
x_{k+1} = \Phi x_k + w_k
\end{equation}

```{python}
from inu import W_EI, A_E, E2
from inu import GRAV_E, GRAV_K, GRAV_F, GRAV_M
import math
import numpy as np
import pandas as pd
from pathlib import Path

def forward_step(
        llh, # lat/long/alt rad,rad,meter
        vne, # meters/second
        ):
    """
    Returns the velocity in in the geodetic frame, i.e. Dllh/Dt
    
    llh
    vne
    """

    # Trig of latitude
    clat = math.cos(llh[0])
    slat = math.sin(llh[0])
    tlat = math.tan(llh[0])

    # Rotation rate of earth relative to inertial
    wneix = W_EI*clat
    wneiz = -W_EI*slat
    
    # Rotation rate of navigation relative to earth
    klat = math.sqrt(1 - E2*slat**2)
    Rt = A_E/klat
    Rm = (Rt/klat**2)*(1 - E2)
    wnnex = vne[1]/(Rt + llh[2])
    wnney = -vne[0]/(Rm + llh[2])
    wnnez = -vne[1]*tlat/(Rt + llh[2])
    
    # Rotation rate of body relative to navigation
    wx = wnnex + wneix
    wy = wnney
    wz = wnnez + wneiz
    Dllh = np.array([wx, wy, wz]) # temp use
    #wbbn = wbbi - Cnb.T @ Dllh
    
    # Position derivatives
    Dllh[0] = -wnney
    Dllh[1] = wnnex/clat
    Dllh[2] = -vne[2]

    return Dllh

llh = np.array([np.radians(35.81), np.radians(-58.54),6180.0])
vne = np.array([0,0,0])

```

with the transition matrix $\Phi$ given by

\begin{equation}
\Phi = 
\end{equation}

## Measurements

There are effectively two types of measurements, 2D and 3D positions. 

### 2D position measurments

The 2D measurements occur with a single WSPR transmission using the [Maidenhead system](https://en.wikipedia.org/wiki/Maidenhead_Locator_System). These positions are accurate only tos a single square. Each square represents 1 degree of latitiude by 2 degrees of longitude. This large area will translate into a large covariance for these position estimates.

### 3D position measurements

When extended WSPR telementry is received a complete GPS 3D position is returned.


```{python}
trackfile = Path('/opt/project/_sources/launches/smore-002/launch/KF8EEZ_109_20251106-20251106.csv')
df = pd.read_csv(trackfile)
df.sort_values('#',inplace=True)
df.set_index('#',inplace=True)

# get times and convert to seconds since launch
t =  pd.to_datetime(df['Time UTC'])
dt = (t - t[1]).dt.total_seconds().to_numpy()

# get llh positon spots
llh = df[['Lat (°)','Lon (°)', 'Altitude (km)',]].to_numpy()
llh[:,0:2] = np.radians(llh[:,0:2]) # convert lat/lon to radians
llh[:,-1] *= 1000.0 # convert to meters, Nan in height means 2D spot, no altitude
```


```{python}
def jacobian(
        llh,
        vne
        ):

    # parse inputs
    lat, _, hae = llh
    vN, vE, vD = vne

    F = np.zeros([6,6])

    # Trig of latitude
    clat = np.cos(lat)
    slat = np.sin(lat)
    clat2 = clat**2
    slat2 = slat**2
    tlat = np.tan(lat)

    # Rotation rate of earth relative to inertial
    wx = W_EI*clat
    wz = -W_EI*slat
    
    # Distance from Earth
    klat = np.sqrt(1 - E2*slat2)
    Rt = A_E/klat
    Rm = (Rt/klat**2)*(1 - E2)
    lt = Rt + hae
    lm = Rm + hae
    
    # Get the partial derivatives with respect to latitude and height.
    y0 = GRAV_E*(1.0 + GRAV_K*slat2)/klat
    nu = 2.0/A_E*(1.0 + GRAV_F + GRAV_M - 2*GRAV_F*slat2)
    eta = 1 + (3/A_E**2)*hae**2 - nu*hae
    Dyl = ((2*GRAV_K*GRAV_E + E2*y0/klat)*eta/klat
        + 8*GRAV_F*y0*hae/A_E)*slat*clat
    Dyh = -y0*nu + y0*6*hae / A_E**2
    
    # dp_dp
    F[0, 2] = -vN/lm**2
    F[1, 0] = vE*tlat/(lt*clat)
    F[1, 2] = -vE/(lt**2*clat)
    # dp_dv
    F[0, 3] = 1/lm
    F[1, 4] = 1/(lt*clat)
    F[2, 5] = -1
    
    # dv_dp
    F[3, 0] = -2*vE*wx - vE**2/(lt*clat2)
    F[3, 2] = vE**2*tlat/lt**2 - vN*vD/lm**2
    F[4, 0] = 2*vN*wx + 2*vD*wz + vN*vE/(lt*clat2)
    F[4, 2] = -vE*(vN*tlat + vD)/lt**2
    F[5, 0] = -2*vE*wz + Dyl
    F[5, 2] = (vN/lm)**2 + (vE/lt)**2 + Dyh
    
    # dv_dv
    F[3, 3] = vD/lm
    F[3, 4] = 2*wz - 2*vE*tlat/lt
    F[3, 5] = vN/lm
    F[4, 3] = -2*wz + vE*tlat/lt
    F[4, 4] = (vN*tlat + vD)/lt
    F[4, 5] = 2*wx + vE/lt
    F[5, 3] = -2*vN/lm
    F[5, 4] = -2*wx - 2*vE/lt

    return F
    
def ekf(
        z_t, # position measurements - llh [Nx3]
        llh0, # initial llh [1x3] 
        vne0, # initial velocity [1x3]
        Q,
        R2d, # [2x2]
        R3d, # [3x3]
        T,   # time deltas from start
        hP0, # initial state covariance matrix
        ):

    # get number of samples
    K = len(T)

    # define constants
    I = np.eye(6)
    H3d = np.zeros([3,6]) # 3D measurement matrix
    H3d[:3,:3] = np.eye(3) # only llh measured
    H2d = np.zeros([2,6]) # 2D measurement matrix
    H2d[:2,:2] = np.eye(2) # only ll measured
    Z = np.zeros([6,6]) # zeros matrix

    # allocate output storage - "hat" variables
    hllh_t = np.zeros([3,K]) # estimated position
    hvne_t = np.zeros([3,K]) # estimated velocity
    hP_t = np.zeros([K,6,6]) # estimated state covariance

    # initialize
    llh = llh0.copy()
    vne = vne0.copy()
    hP = hP0.copy()
    
    # start an estimation loop
    for k in range(K):
        z = z_t[:,k]
        if np.isnan(z[-1]):
            # 2D measurement case
            H = H2d
            R = R2d
            r = z[0:2] - llh[0:2] # innovation
        else:
            # 3D measurement case
            H = H3d
            R = R3d
            r = z - llh # innovation

        print(f'{k} llh = {llh}')
        print(f'{k} r   = {r}')

        S = H @ hP @ H.T + R
        Si = np.linalg.inv(S)
        Kg = hP @ H.T @ Si
        hP -= Kg @ H @ hP
        dx = Kg @ r
        llh += dx[:3]
        vne += dx[3:6]

        # save the results
        hllh_t[:,k] = llh.copy()
        hvne_t[:,k] = vne.copy()
        hP_t[k,:,:] =  hP.copy()

        # forward propagate for next step
        F = jacobian(llh, vne,)
        Phi = I + (F*T[k])@(I + (F*T[k]/2)) # 2nd-order expm(F T)
        hP = Phi @ hP @ Phi.T + Q

        # Get the state derivatives.
        Dllh = forward_step(llh, vne,)       

        # Integrate (forward Euler for position and velocity,
        # matrix product for attitude).
        llh += Dllh * T[k]         # change applies linearly
        #vne += Dvne * T[i]         # change applies linearly

    return hllh_t, hvne_t, hP_t

# measurement noise
R2d = np.diag([np.radians(1.0), np.radians(1.0)])**2
R3d = np.diag([np.radians(0.01), np.radians(0.01), 10.0])**2

# process noise
# zero for position
# 10 m/s for velocity
Q = np.diag([
    0,
    0,
    0,
    10,
    10,
    10,])**2

# initial covariance
# 0.01 deg, 10 feet, 10 m/s
hP0 = np.diag([
    np.radians(0.01),
    np.radians(0.01),
    10,
    10,
    10,
    10,
])**2

hllh_t, hvne_t, hP_t = ekf(
    llh.T,
    llh.T[:,1],
    np.array([0.0,0.0,0.0]), # initial veocity
    Q, #  # process noise 6,6
    R2d, # 2D measurement noise
    R3d, # 3D measurement noise
    dt[1:],
    hP0, # initial covariance
    )
    

```
