{
  "hash": "9c7f913583512c89708d1697fdbb6574",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Antennae build information\nformat:\n  html:\n    toc: true\n---\n\n\n# GPS\n\n\n## GPS dipole antenna\n\nFrom the u4b hardware manual, page 12\n\n```\nThe GPS antenna can be made of simple #28 (0.3mm) enameled wire; a 1/4-wave at 1575Mhz is\nabout 45mm. The feedline consists of 1-inch of twisted wire, about 6 turns works well.\n```\n\n::: {#gps-wavelength .cell execution_count=1}\n``` {.python .cell-code}\nfrom astropy import units as u\nfrom astropy.constants import c\nfreq_l1 = 1575.42e6 * u.Hz # Hz\n\nwavelength = c/freq_l1\n\nhalf_wavelength = wavelength/2.0\nquarter_wavelength = wavelength/4.0\nquarter_wavelength95 = wavelength/4.0*0.95\n\nprint(f'full wavelength: {wavelength.to(u.millimeter)}')\nprint(f'half wavelength: {half_wavelength.to(u.millimeter)} ')\nprint(f'quarter wavelength: {quarter_wavelength.to(u.millimeter)} ')\nprint(f'quarter wavelength * 95%: {quarter_wavelength95.to(u.millimeter)} ')\n\n# feedline additional length\nfeed_length = 1.0*u.imperial.inch\n\nprint(f'feed length: {feed_length.to(u.millimeter)}')\n\n# total length\ntotlength = feed_length + quarter_wavelength95\nprint(f'total length: {totlength.to(u.millimeter)}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfull wavelength: 190.29367279836487 mm\nhalf wavelength: 95.14683639918243 mm \nquarter wavelength: 47.57341819959122 mm \nquarter wavelength * 95%: 45.194747289611655 mm \nfeed length: 25.400000000000002 mm\ntotal length: 70.59474728961166 mm\n```\n:::\n:::\n\n\nhalf wavelength: 95.14683639918243 millimeters\nquarter wavelength: 47.57341819959122 millimeters\nquarter wavelength * 95%: 45.194747289611655 mm\nfeed length: 25.400000000000002 mm\ntotal length: 70.59474728961166 mm\n\n\n\n\n# HF\n\n\n\n## HF Antenna\n\n```\nThe HF antenna needs 1/4-wavelength on each leg (for example, each leg is 5m for 20m\noperation). A typical flight configuration has the top end of the top leg tied to the balloon, and the\nU4B payload suspended directly in the middle of the dipole.\n```\n\n### Dummy load\n\nuse a 50 Ohm resistor across the lead pads\n\n### Dipole\n\nFrequency of channel is: 14097060\n\nhttps://www.onlineconversion.com/frequency_wavelength.htm\n\n::: {#wavelength-20m-band .cell execution_count=2}\n``` {.python .cell-code}\nfrom astropy import units as u\nfrom astropy.constants import c\n\nfreq_hf = 14097060 * u.Hz\nwavelength = c/freq_hf\n\nhalf_wavelength = wavelength/2.0\nquarter_wavelength = wavelength/4.0\n\nprint(f'full wavelength: {wavelength.si}')\nprint(f'half wavelength: {half_wavelength.si} ')\nprint(f'quarter wavelength: {quarter_wavelength.si} ')\nprint(f'quarter wavelength: {quarter_wavelength.to(u.imperial.foot)}')\nprint(f'quarter wavelength: {quarter_wavelength.to(u.imperial.inch)}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfull wavelength: 21.26631070592024 m\nhalf wavelength: 10.63315535296012 m \nquarter wavelength: 5.31657767648006 m \nquarter wavelength: 17.442840145931953 ft\nquarter wavelength: 209.31408175118344 inch\n```\n:::\n:::\n\n\nfull wavelength: 21.26631070592024 m\nhalf wavelength: 10.63315535296012 m \nquarter wavelength: 5.31657767648006 m \nquarter wavelength: 17.442840145931953 ft\nquarter wavelength: 209.31408175118344 inch\n\nAntenna wire - what gauge? people are using 36 AWG\nWhat fishing line support to use.\n\nthis note indicates that the antenna length should be shortened by 95%\nhttps://groups.io/g/picoballoon/topic/34545561#msg48\n\nshortening the hf antenna\n\n::: {#60f9101a .cell execution_count=3}\n``` {.python .cell-code}\nquarter_wavelength95 = wavelength/4.0*0.95\nprint(f'quarter wavelength * 95%: {quarter_wavelength95.to(u.imperial.inch)}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nquarter wavelength * 95%: 198.84837766362426 inch\n```\n:::\n:::\n\n\nquarter wavelength * 95%: 198.84837766362426 inch\n\n\n### Magnetic loop antenna\n\nFor receiving and test at launch site, use a mag loop antenna.\nSee: https://codeberg.org/KF8EEZ/magnetic-loop-antennae\n\n",
    "supporting": [
      "antennae_files"
    ],
    "filters": [],
    "includes": {}
  }
}