## Pre-launch design and preparations

- u4b tracker
  - [u4b-004](/_sources/u4b/u4b_004.qmd)
- zener diode regulation
  - [x] test design on breadboard with power supply
  - [ ] compare design with voltage regulator
  - [ ] ordered 1 Watt zener 2026-02-16
- supercaps x2
  - [x] solder together 
- 3 half solar panels
  - schottkey diodes
- HF antenna - 20m band
  - [ ] determine attachment points
  - [x] measure and wind both antenna arms
- GPS antenna
  - [x] build 
  - [x] tested worked with tracker
- 2 balloons
  - [ ] stretch
  - [ ] leak test
  - [ ] suck out air
  - [ ] get helium, ordered [2026-02-16]
- WSPR channel selection
  - planning channel 567, 2 minutes after, 14,097,060 MHz
  - registered in QRP-labs database as smore-003 [2026-02-08]
  - tried to register in [traquito system](https://traquito.github.io/channelmap/), but doesn't work [2026-02-08]

## Payload weight 

- USB connector removed from U4B.
- With antenna winders: 31.7 gram.
- Antenna winder 1 (bottom): 6.2 gram
- Bottom antenna + winder: 8.5 g (200 inches wire)
- Antenna winder 2 (top): 6.2 gram
- Bottom antenna + winder: 10 gram (200 inches wire + fish line)
- Total antenna winder: 15 gram
- Payload weight: 16.7 gram

## Balloon filling calculations

See [Balloon filling calculations for earlier flight](/launches/2025-11-06-smore-002/balloon-filling.qmd)

## Launch checklist

### Pre-launch

- [ ] check forecast for wind and clouds
- [ ] fill balloons

### At launch site

- [ ] verify wind and clouds OK
- [ ] check payload voltage in sun
- [ ] check WSPR transmissions on ground with SDR Rx

## Testing

{{< include /_sources/launches/smore-002/testing/testing.qmd >}}

## Payload design

[S'more 002 payload design](/launches/2025-11-06-smore-002/design.qmd)

## U4B and programming information

{{< include /_sources/u4b/u4b_003.qmd >}}
